name: Main Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: |
          corepack enable
          corepack prepare pnpm@10.3.0

      - name: Use cached Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: pnpm
      - name: Cache purescript files
        uses: actions/cache@v4
        with:
          key: spago-${{ hashFiles('packages/purescript-fns/spago.*') }}
          path: |
            packages/purescript-fns/.spago
            packages/purescript-fns/output

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run test

      - run: pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist

  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: |
          corepack enable
          corepack prepare pnpm@10.3.0

      - name: Use cached Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: pnpm
      - name: Cache purescript files
        uses: actions/cache@v4
        with:
          key: spago-${{ hashFiles('packages/purescript-fns/spago.*') }}
          path: |
            packages/purescript-fns/.spago
            packages/purescript-fns/output
      - run: pnpm install --frozen-lockfile
      - run: pnpm run e2e-test
      - name: Upload test results for svelte-4
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-svelte-4
          path: packages/svelte-4/test-results
          if-no-files-found: ignore
      - name: Upload test results for svelte-5
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-svelte-5
          path: packages/svelte-5/test-results
          if-no-files-found: ignore

  publish:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: dist
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          branch: ${{ github.ref_name }}
